// Generated by sync/sync.js from the TTRPG Wiki vault on 2026-10-04.
// Do not edit by hand: change the vault or sync/overrides.json and run `node sync/sync.js`.

const campaigns = [
    "Curse of Strahd",
    "Tomb of Horrors",
    "Waterdeep: Dragon Heist",
    "Orrery of the Wanderer",
    "Borca",
    "Wild Beyond the Witchlight",
    "Strixhaven: Year 1",
    "Dungeon of the Mad Mage",
    "Lost Laboratory of Kwalish",
    "City of Eyes",
    "Star Wars: Stranded on Parnassos",
    "Journeys through the Radiant Citadel",
    "Menace Under Otari",
    "Re: Strahd",
    "Volo's Guide to Getting Murdered",
    "Objects of Interest: Forged in Fire",
    "Chains of Asmodeus"
];

const characters = [
    {
        "Name": "Abel",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Abi-Dalzim",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Abigor",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Abriel Redchord",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Achlys",
        "Campaigns": [
            { "Name": "Borca", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Adramalech",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Aelvette",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Aetna",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Amelia",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Amidor",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ammisyll Veldann",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Anagwendol",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Anastrasya Karelova (Scaena)",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Andros",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "Player" }
        ]
    },
    {
        "Name": "Arabelle Zsoltsy (Scaena)",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Aran Tal",
        "Campaigns": [
            { "Name": "Star Wars: Stranded on Parnassos", "Role": "NPC" }
        ]
    },
    {
        "Name": "Aranya",
        "Campaigns": [
            { "Name": "Phantasms of Sri Raji", "Role": "Player" }
        ]
    },
    {
        "Name": "Aren",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "Player" }
        ]
    },
    {
        "Name": "Aurora",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Aurora de L'aunaie",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Avi",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Azure",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Baalzebul",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Babolax",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Balzac",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Barachiel",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Baron Vallakovich",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Bavlorna Blightstraw",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Belial",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Bella (Scaena)",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Belle Mere",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Birroo",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Blaedswith Ashenwynd",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "Player" }
        ]
    },
    {
        "Name": "Blightmar",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Blinksy",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Bloody Toes",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Bone Devil",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Bonespur",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Brawn",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Breadstick Fundi",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Brenneth",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Briar",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "Player" },
            { "Name": "Orrery of the Wanderer", "Role": "Player" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "Player" }
        ]
    },
    {
        "Name": "Brok",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Brynhilda Pedersen",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Cadoras",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Calenhad Strongheart",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Calor Galateth",
        "Campaigns": [
            { "Name": "Star Wars: Stranded on Parnassos", "Role": "Player" }
        ]
    },
    {
        "Name": "Candlefoot",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Casavel",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "Player" }
        ]
    },
    {
        "Name": "Charm",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Cheshire",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Chococo",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Christopher",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Chun Hana",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Cicero",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Clapperclaw",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Clara",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Colleen Thimble",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "Player" }
        ]
    },
    {
        "Name": "Cornelius Brassgrave",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Corteso",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Crypta",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "Player" }
        ]
    },
    {
        "Name": "Dandelion",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Daphne",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Darcy",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Darribeth",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Davil",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "NPC" }
        ]
    },
    {
        "Name": "Deannach",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Dr. Brains",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Dr. Zakari",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Drazhomir",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Dre Hilltop",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Dumphrey Frogart",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Durge",
        "Campaigns": [
            { "Name": "Star Wars: Stranded on Parnassos", "Role": "NPC" }
        ]
    },
    {
        "Name": "Dusty",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Dyre",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "Player" },
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Eclipse",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ecstasy",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Elidon",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Elkhorn",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ellis Hilltop",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Elysia Saltwound",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Embric",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Emmek",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" }
        ]
    },
    {
        "Name": "Emran Sur",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Endelyn Moongrave",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Erasmus",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Escher",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Esha",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "Player" }
        ]
    },
    {
        "Name": "Esvele",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Evard",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Evie",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "Player" },
            { "Name": "Orrery of the Wanderer", "Role": "Player" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "Player" }
        ]
    },
    {
        "Name": "Ewyn",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "NPC" }
        ]
    },
    {
        "Name": "Exethanter",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ezmerelda",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "Tomb of Horrors", "Role": "NPC" },
            { "Name": "Borca", "Role": "Player" },
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "Strixhaven: Year 1", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ezmerelda Love",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ezra",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Faladdin Blackhelm",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Father Taps",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Fayelara Kos",
        "Campaigns": [
            { "Name": "Menace Under Otari", "Role": "Player" }
        ]
    },
    {
        "Name": "Fayphena Forefog",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Feenia",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Felrax",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Fen",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "Player" },
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Firan Zal'Honan",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Fizhgerald",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Floon",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Foulsham",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Fox",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Objects of Interest: Forged in Fire", "Role": "Player" }
        ]
    },
    {
        "Name": "Frahl",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Francis Adelir",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "Player" }
        ]
    },
    {
        "Name": "Franz Ismarkovich",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Freek",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" },
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Frerk",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Gage",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "Player" }
        ]
    },
    {
        "Name": "Gallagher Love",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "Player" }
        ]
    },
    {
        "Name": "Gaunt Silhouette",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Gearbox",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Genevayne",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Gennifer Weathermay-Foxgrove",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Gildha",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Glasya",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Gleam",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Glister",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Glitter Dew",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Gloine Nathair-Nathair",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Godfrey",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Gorkoh",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Grayson",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Grayson Love",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Greeter",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Gren",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Grunka",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Guthildi",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "Strixhaven: Year 1", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Halleth",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Hati",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Helga Ruvak",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Hrangor",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Iabrochorum",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "IMPALA",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ingrid",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ireena",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "Tomb of Horrors", "Role": "NPC" },
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ireena von Zarovich",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Isabella",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Isaias Damasio",
        "Campaigns": [
            { "Name": "Menace Under Otari", "Role": "Player" }
        ]
    },
    {
        "Name": "Ismark",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ismark Kolyanovich (Scaena)",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Itzmin del Prado",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ivan",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ivana",
        "Campaigns": [
            { "Name": "Borca", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ives Ismarkovich",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Jari",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "Player" }
        ]
    },
    {
        "Name": "Javenesh",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Jean-Baptiste Escher (Scaena)",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Jenevere",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Jery",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ji-me Vidio",
        "Campaigns": [
            { "Name": "Star Wars: Stranded on Parnassos", "Role": "Player" }
        ]
    },
    {
        "Name": "Jim Darkmagic",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Jingle Jangle",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Jirko Ismarkovich",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Joan Hargrave",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Johannes",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Jord",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Jorn",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Juniper",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Jutt",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Kala Mabarin",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Kallessk",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Kargan Skul",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ker",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Kholtris",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Kianna",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "King Doerdon",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Kira Risk",
        "Campaigns": [
            { "Name": "Menace Under Otari", "Role": "Player" }
        ]
    },
    {
        "Name": "Kitty",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "Player" }
        ]
    },
    {
        "Name": "Klendisk",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Koh Tam",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Kordichai",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Krue",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "Player" },
            { "Name": "Tomb of Horrors", "Role": "Player" },
            { "Name": "Borca", "Role": "Player" },
            { "Name": "Wild Beyond the Witchlight", "Role": "Player" },
            { "Name": "City of Eyes", "Role": "Player" },
            { "Name": "Re: Strahd", "Role": "Player" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "Player" }
        ]
    },
    {
        "Name": "Kwalish",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Kyward Apostasio",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "Player" }
        ]
    },
    {
        "Name": "La Fata",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Lacrymosa",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Lamorna",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Lang",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Larine",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Larisa Sur",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Laurie Weathermay-Foxgrove",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Lemont Sediam Juste",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Lif",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Liko",
        "Campaigns": [
            { "Name": "Menace Under Otari", "Role": "Player" }
        ]
    },
    {
        "Name": "Little Balzac",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Little Strahd",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Lottie",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Lucian",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ludmilla Love",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Lurker",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Lynx",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "Player" }
        ]
    },
    {
        "Name": "Lyssa von Zarovich",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Madryck Roslof",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Magaggog Bootbottle",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mani",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "Player" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Maria Adelir",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Marsh",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "Player" }
        ]
    },
    {
        "Name": "Mary",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mattrim",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Meff",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Melo Sur",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Melwythorne",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mephistopheles",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mina",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Minsc",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mirabelle",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mirror Nia",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Molliver",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Morax",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Morcades Gable",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mordenkainen",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Morty",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mr. Light",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mr. Witch",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Myrtle",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" },
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mystic",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "Player" }
        ]
    },
    {
        "Name": "Nassari",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Neferon",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Nia",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "Player" },
            { "Name": "Tomb of Horrors", "Role": "Player" },
            { "Name": "Wild Beyond the Witchlight", "Role": "Player" },
            { "Name": "City of Eyes", "Role": "Player" },
            { "Name": "Re: Strahd", "Role": "Player" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "Player" }
        ]
    },
    {
        "Name": "Nim",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Nora",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Nostalia",
        "Campaigns": [
            { "Name": "Borca", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Notte von Zarovich",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "Player" }
        ]
    },
    {
        "Name": "Nurse Joy",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Oberon",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ōdachi",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Oddlewin",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Old Death",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Omin",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Orcades Gable",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Orishada",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Osybus",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Otis",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ottelie",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Paloma",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Patsky",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Pazrodine",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Petre Teodorus",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Pewter",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Pidlwick",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Pietra van Riese",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Pollenella",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Porter",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Prismari",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Prydevere",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Quentillius",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Quevven Teh'Kinrellz",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Quincey Pasqual Morris (Scaena)",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rahadin",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rahadin Zdravkov (Scaena)",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ramius Dangremond",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rampart",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Renaer",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" }
        ]
    },
    {
        "Name": "Reynard Ratflea",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rictavio",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "Tomb of Horrors", "Role": "NPC" },
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "NPC" }
        ]
    },
    {
        "Name": "Risk",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rizzeryl",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Roberta",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Robi Junior (Pidlwick III)",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Roneca",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rosa",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rosie",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rubina",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rudolph",
        "Campaigns": [
            { "Name": "Borca", "Role": "NPC" },
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ruik",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "Player" },
            { "Name": "Orrery of the Wanderer", "Role": "Player" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "Player" }
        ]
    },
    {
        "Name": "Rupert Deadbolt",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ruslana",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rusty Bucket",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ruxa",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Sackville Grabbins",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Samira Arah",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Sandman",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Seku Awaud",
        "Campaigns": [
            { "Name": "Star Wars: Stranded on Parnassos", "Role": "Player" }
        ]
    },
    {
        "Name": "Selise",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Serapio",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Shanix Breakrattle",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Shuvadri",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Sildar",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Silver",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "Player" }
        ]
    },
    {
        "Name": "Sir Talavar",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Skabatha Nightshade",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Skeemo Weirdbottle",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" }
        ]
    },
    {
        "Name": "Skelly",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Skoll",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "Player" },
            { "Name": "Tomb of Horrors", "Role": "Player" },
            { "Name": "Wild Beyond the Witchlight", "Role": "Player" },
            { "Name": "City of Eyes", "Role": "Player" },
            { "Name": "Re: Strahd", "Role": "Player" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "Player" }
        ]
    },
    {
        "Name": "Sonja Florakis",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "Player" }
        ]
    },
    {
        "Name": "Stella von Zarovich",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Strahd",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Strashka Relvaunder",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Struthio",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Sumari",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "Player" }
        ]
    },
    {
        "Name": "Sylqen Silverwatch",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Synestia Whitechapel",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Talanatha",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Tashlyn",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Telphusa",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ten",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Tenser",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Thaco",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Thalia",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "The Abbot (Jude Law)",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "The Cat Lord",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "The Fisher King",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "The Painted Lady",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "The Spider",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Thetsis",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Tiax",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Tilana",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Titan",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "To'vvag'das'vak'thur'ai'thumonic'ar of the Greater Eye",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Tordit",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Trench",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" }
        ]
    },
    {
        "Name": "Trilla",
        "Campaigns": [
            { "Name": "Volo's Guide to Getting Murdered", "Role": "Player" }
        ]
    },
    {
        "Name": "Tsu",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Tullus",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Tungsten Ward",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Tzunk",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Urzmaktok",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Vajra",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "NPC" }
        ]
    },
    {
        "Name": "Vasilka (Scaena)",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Velastrias",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Victor",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Victor Vallakovich (Scaena)",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Vih'zel",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "Player" }
        ]
    },
    {
        "Name": "Vito Romenza",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Volenta Popofsky (Scaena)",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Volo",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "NPC" }
        ]
    },
    {
        "Name": "Vyldara",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Wester",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Whippoorwill",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Whisper",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Will of the Feywild",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Wizzy",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Wobbles",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Woe Ismae",
        "Campaigns": [
            { "Name": "Star Wars: Stranded on Parnassos", "Role": "Player" }
        ]
    },
    {
        "Name": "Yagra",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" },
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Yarnspinner",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Yek",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Yesper",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Yesper Taltos (Scaena)",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ygor",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Yurk",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Yves Kolyanovich",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "Player" }
        ]
    },
    {
        "Name": "Zanther",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Zaria",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Zilitsa",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ziraj",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" }
        ]
    },
    {
        "Name": "Zybilna",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    }
];
