// Generated by sync/sync.js from the TTRPG Wiki vault on 2026-10-04.
// Do not edit by hand: change the vault or sync/overrides.json and run `node sync/sync.js`.

const campaigns = [
    { "Name": "Curse of Strahd", "Cover": "covers/curse-of-strahd.webp" },
    { "Name": "Tomb of Horrors", "Cover": "covers/tomb-of-horrors.webp" },
    { "Name": "Waterdeep: Dragon Heist", "Cover": "covers/waterdeep-dragon-heist.webp" },
    { "Name": "Orrery of the Wanderer", "Cover": "covers/orrery-of-the-wanderer.webp" },
    { "Name": "Borca", "Cover": "covers/borca.webp" },
    { "Name": "Wild Beyond the Witchlight", "Cover": "covers/wild-beyond-the-witchlight.webp" },
    { "Name": "Strixhaven: Year 1", "Cover": "covers/strixhaven-year-1.webp" },
    { "Name": "Dungeon of the Mad Mage", "Cover": "covers/dungeon-of-the-mad-mage.webp" },
    { "Name": "Lost Laboratory of Kwalish", "Cover": "covers/lost-laboratory-of-kwalish.webp" },
    { "Name": "City of Eyes", "Cover": "covers/city-of-eyes.webp" },
    { "Name": "Star Wars: Stranded on Parnassos", "Cover": "covers/star-wars-stranded-on-parnassos.webp" },
    { "Name": "Journeys through the Radiant Citadel", "Cover": "covers/journeys-through-the-radiant-citadel.webp" },
    { "Name": "Menace Under Otari", "Cover": "covers/menace-under-otari.webp" },
    { "Name": "Re: Strahd", "Cover": "covers/re-strahd.webp" },
    { "Name": "Volo's Guide to Getting Murdered", "Cover": "covers/volo-s-guide-to-getting-murdered.webp" },
    { "Name": "Objects of Interest: Forged in Fire", "Cover": "covers/objects-of-interest-forged-in-fire.webp" },
    { "Name": "Chains of Asmodeus", "Cover": "covers/chains-of-asmodeus.webp" }
];

const characters = [
    {
        "Name": "Abel",
        "Status": "Alive",
        "Portrait": "portraits/abel-brentstock.webp",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Abi-Dalzim",
        "Status": "Alive",
        "Portrait": "portraits/abi-dalzim.webp",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Abigor",
        "Status": "Dead",
        "Portrait": "portraits/abigor.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Abriel Redchord",
        "Status": "Alive",
        "Portrait": "portraits/abriel-redchord.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Achlys",
        "Status": "Alive",
        "Portrait": "portraits/achlys.webp",
        "Campaigns": [
            { "Name": "Borca", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Adramalech",
        "Status": "Dead",
        "Portrait": "portraits/adramalech.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Aelvette",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Aetna",
        "Status": "Alive",
        "Portrait": "portraits/aetna.webp",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Amelia",
        "Status": "Alive",
        "Portrait": "portraits/amelia-hawthorne.webp",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Amidor",
        "Status": "Alive",
        "Portrait": "portraits/amidor.webp",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ammisyll Veldann",
        "Status": "Alive",
        "Portrait": "portraits/ammisyll-veldann.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Anagwendol",
        "Status": "Alive",
        "Portrait": "portraits/anagwendol.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Anastrasya Karelova (Scaena)",
        "Status": "Alive",
        "Portrait": "portraits/anastrasya-karelova-scaena.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Andros",
        "Status": "Alive",
        "Portrait": "portraits/andros.webp",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "Player", "Player": "Rory", "Description": "an asmodeus tiefling sorcerer (wild magic)" }
        ]
    },
    {
        "Name": "Arabelle Zsoltsy (Scaena)",
        "Status": "Alive",
        "Portrait": "portraits/arabelle-zsoltsy-scaena.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Aran Tal",
        "Status": "Alive",
        "Portrait": "portraits/aran-tal.webp",
        "Campaigns": [
            { "Name": "Star Wars: Stranded on Parnassos", "Role": "NPC" }
        ]
    },
    {
        "Name": "Aranya",
        "Status": "Alive",
        "Portrait": "portraits/aranya.webp",
        "Campaigns": [
            { "Name": "Phantasms of Sri Raji", "Role": "Player" }
        ]
    },
    {
        "Name": "Aren",
        "Status": "Alive",
        "Portrait": "portraits/aren-romenza.webp",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "Player", "Player": "Jett", "Description": "a half vistani human / wood elf ranger (monster slayer)" }
        ]
    },
    {
        "Name": "Aurora",
        "Status": "Alive",
        "Portrait": "portraits/aurora-luna-wynterstarr.webp",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Aurora de L'aunaie",
        "Status": "Alive",
        "Portrait": "portraits/aurora-de-l-aunaie.webp",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Avi",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Azure",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Baalzebul",
        "Status": "Alive",
        "Portrait": "portraits/baalzebul.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Babolax",
        "Status": "Alive",
        "Portrait": "portraits/babolax.webp",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Balzac",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Barachiel",
        "Status": "Alive",
        "Portrait": "portraits/barachiel.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Baron Vallakovich",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Bavlorna Blightstraw",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Belial",
        "Status": "Alive",
        "Portrait": "portraits/belial.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Bella (Scaena)",
        "Status": "Alive",
        "Portrait": "portraits/bella-scaena.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Belle Mere",
        "Status": "Alive",
        "Portrait": "portraits/belle-mere.webp",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Birroo",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Blaedswith Ashenwynd",
        "Status": "Alive",
        "Portrait": "portraits/blaedswith-ashenwynd.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "Player", "Player": "Connor", "Description": "a high elf paladin (oathbreaker-turned-oath of redemption)" }
        ]
    },
    {
        "Name": "Blightmar",
        "Status": "Dead",
        "Portrait": "portraits/blightmar.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Blinksy",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Bloody Toes",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Bone Devil",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Bonespur",
        "Status": "Alive",
        "Portrait": "portraits/bonespur.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Brawn",
        "Status": "Alive",
        "Portrait": "portraits/brawn-mcgable.webp",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Breadstick Fundi",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Brenneth",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Briar",
        "Status": "Alive",
        "Portrait": "portraits/briar-de-l-aunaie.webp",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "Player", "Player": "Jett", "Description": "a reborn warlock (great old ones)" },
            { "Name": "Orrery of the Wanderer", "Role": "Player", "Player": "Jett", "Description": "a reborn warlock (great old ones)" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "Player", "Player": "Jett", "Description": "a reborn warlock-turned-sorcerer (clockwork soul)" }
        ]
    },
    {
        "Name": "Brok",
        "Status": "Alive",
        "Portrait": "portraits/brok.webp",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Brynhilda Pedersen",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Cadoras",
        "Status": "Alive",
        "Portrait": "portraits/cadoras-damellawar.webp",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Calenhad Strongheart",
        "Status": "Alive",
        "Portrait": "portraits/calenhad-strongheart.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Calor Galateth",
        "Status": "Alive",
        "Portrait": "portraits/calor-galateth.webp",
        "Campaigns": [
            { "Name": "Star Wars: Stranded on Parnassos", "Role": "Player", "Player": "Connor", "Description": "a kiffar sentinel" }
        ]
    },
    {
        "Name": "Candlefoot",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Casavel",
        "Status": "Alive",
        "Portrait": "portraits/casavel-hlaeraheal.webp",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "Player", "Player": "Rory", "Description": "a sun elf wizard (bladesinging)" }
        ]
    },
    {
        "Name": "Charm",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Cheshire",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Chococo",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Christopher",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Chun Hana",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Cicero",
        "Status": "Alive",
        "Portrait": "portraits/cicero.webp",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Clapperclaw",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Clara",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Colleen Thimble",
        "Status": "Alive",
        "Portrait": "portraits/colleen-thimble.webp",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "Player", "Player": "Callista", "Description": "a human savant (investigator)" }
        ]
    },
    {
        "Name": "Cornelius Brassgrave",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Corteso",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Crypta",
        "Status": "Alive",
        "Portrait": "portraits/crypta.webp",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "Player", "Player": "Jett", "Description": "a half goblin/elf (devkarin) necromancer (blood ascendant)" }
        ]
    },
    {
        "Name": "Dandelion",
        "Status": "Alive",
        "Portrait": "portraits/dandelion.webp",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Daphne",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Darcy",
        "Status": "Alive",
        "Portrait": "portraits/darcelle-eversea.webp",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Darribeth",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Davil",
        "Status": "Alive",
        "Portrait": "portraits/davil-starsong.webp",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "NPC" }
        ]
    },
    {
        "Name": "Deannach",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Dr. Brains",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Dr. Zakari",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Drazhomir",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Dre Hilltop",
        "Status": "Alive",
        "Portrait": "portraits/dre-hilltop.webp",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Dumphrey Frogart",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Durge",
        "Status": "Alive",
        "Portrait": "portraits/durge.webp",
        "Campaigns": [
            { "Name": "Star Wars: Stranded on Parnassos", "Role": "NPC" }
        ]
    },
    {
        "Name": "Dusty",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Dyre",
        "Status": "Alive",
        "Portrait": "portraits/dyre-longstrider.webp",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "Player", "Player": "Jett", "Description": "a reborn drow bard (college of satire)" },
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Eclipse",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ecstasy",
        "Status": "Alive",
        "Portrait": "portraits/ecstasy.webp",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Elidon",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Elkhorn",
        "Status": "Alive",
        "Portrait": "portraits/elkhorn.webp",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ellis Hilltop",
        "Status": "Alive",
        "Portrait": "portraits/ellis-hilltop.webp",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Elysia Saltwound",
        "Status": "Alive",
        "Portrait": "portraits/elysia-saltwound.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Embric",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Emmek",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" }
        ]
    },
    {
        "Name": "Emran Sur",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Endelyn Moongrave",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Erasmus",
        "Status": "Dead",
        "Portrait": "portraits/erasmus-van-richten.webp",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Escher",
        "Status": "Alive",
        "Portrait": "portraits/jean-baptiste-escher.webp",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Esha",
        "Status": "Alive",
        "Portrait": "portraits/esha.webp",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "Player", "Player": "Rory", "Description": "a half-orc rogue (arcane trickster)" }
        ]
    },
    {
        "Name": "Esvele",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Evard",
        "Status": "Alive",
        "Portrait": "portraits/evard.webp",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Evie",
        "Status": "Alive",
        "Portrait": "portraits/evaline-rajarn.webp",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "Player", "Player": "Callista", "Description": "an animated armor fighter (eldritch knight)" },
            { "Name": "Orrery of the Wanderer", "Role": "Player", "Player": "Callista", "Description": "an animated armor fighter (eldritch knight)" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "Player", "Player": "Callista", "Description": "a half-elf fighter (eldritch knight)" }
        ]
    },
    {
        "Name": "Ewyn",
        "Status": "Alive",
        "Portrait": "portraits/ewyn-the-divine-vorpal-moonblade.webp",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "NPC" }
        ]
    },
    {
        "Name": "Exethanter",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ezmerelda",
        "Status": "Alive",
        "Portrait": "portraits/ezmerelda-d-avenir.webp",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "Tomb of Horrors", "Role": "NPC" },
            { "Name": "Borca", "Role": "Player", "Player": "Lup", "Description": "a vistani human fighter (eldritch knight)" },
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "Strixhaven: Year 1", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ezmerelda Love",
        "Status": "Alive",
        "Portrait": "portraits/ezmerelda-love.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ezra",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Faladdin Blackhelm",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Father Taps",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Fayelara Kos",
        "Status": "Alive",
        "Portrait": "portraits/fayelara-kos.webp",
        "Campaigns": [
            { "Name": "Menace Under Otari", "Role": "Player", "Player": "Callista", "Description": "a half-elf, half-orc fighter" }
        ]
    },
    {
        "Name": "Fayphena Forefog",
        "Status": "Alive",
        "Portrait": "portraits/fayphena-forefog.webp",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Feenia",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Felrax",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Fen",
        "Status": "Alive",
        "Portrait": "portraits/fen-ruldegost.webp",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "Player", "Player": "Rory", "Description": "an water genasi cleric (peace domain)" },
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Firan Zal'Honan",
        "Status": "Alive",
        "Portrait": "portraits/firan-zal-honan.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Fizhgerald",
        "Status": "Alive",
        "Portrait": "portraits/fizhgerald.webp",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Floon",
        "Status": "Alive",
        "Portrait": "portraits/floon-blagmaar.webp",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Foulsham",
        "Status": "Alive",
        "Portrait": "portraits/foulsham.webp",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Fox",
        "Status": "Alive",
        "Portrait": "portraits/fox-d-avenir.webp",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Objects of Interest: Forged in Fire", "Role": "Player", "Player": "Lup", "Description": "a near-human knight (code of the adventurer)" }
        ]
    },
    {
        "Name": "Frahl",
        "Status": "Alive",
        "Portrait": "portraits/frahl-boartrap.webp",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Francis Adelir",
        "Status": "Alive",
        "Portrait": "portraits/francis-adelir.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "Player", "Player": "Jett", "Description": "a reborn warlock (pact of the undead turned pact of the first vampire turned pact of the hunter in darkness)" }
        ]
    },
    {
        "Name": "Franz Ismarkovich",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Freek",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" },
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Frerk",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Gage",
        "Status": "Alive",
        "Portrait": "portraits/gage-kamdyn.webp",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "Player", "Player": "Connor", "Description": "a reborn human necromancer (reanimator)" }
        ]
    },
    {
        "Name": "Gallagher Love",
        "Status": "Alive",
        "Portrait": "portraits/gallagher-love.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "Player", "Player": "Rory", "Description": "a human wizard (school of war)" }
        ]
    },
    {
        "Name": "Gaunt Silhouette",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Gearbox",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Genevayne",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Gennifer Weathermay-Foxgrove",
        "Status": "Alive",
        "Portrait": "portraits/gennifer-weathermay-foxgrove.webp",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Gildha",
        "Status": "Alive",
        "Portrait": "portraits/gildha-duhn.webp",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Glasya",
        "Status": "Alive",
        "Portrait": "portraits/glasya.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Gleam",
        "Status": "Alive",
        "Portrait": "portraits/gleam-selenelion.webp",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Glister",
        "Status": "Alive",
        "Portrait": "portraits/glister-selenelion.webp",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Glitter Dew",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Gloine Nathair-Nathair",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Godfrey",
        "Status": "Dead",
        "Portrait": "portraits/godfrey-gwilym.webp",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Gorkoh",
        "Status": "Alive",
        "Portrait": "portraits/gorkoh-nightrattle.webp",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Grayson",
        "Status": "Alive",
        "Portrait": "portraits/grayson-wildemere.webp",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Grayson Love",
        "Status": "Alive",
        "Portrait": "portraits/grayson-love.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Greeter",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Gren",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Grunka",
        "Status": "Alive",
        "Portrait": "portraits/grunka-shatterstone.webp",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Guthildi",
        "Status": "Alive",
        "Portrait": "portraits/guthildi-alabastrus-bloodquake-iv.webp",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "Strixhaven: Year 1", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Halleth",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Hati",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Helga Ruvak",
        "Status": "Alive",
        "Portrait": "portraits/helga-ruvak.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Hrangor",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Iabrochorum",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "IMPALA",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ingrid",
        "Status": "Dead",
        "Portrait": "portraits/ingrid-van-richten.webp",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ireena",
        "Status": "Alive",
        "Portrait": "portraits/ireena-astorio.webp",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "Tomb of Horrors", "Role": "NPC" },
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ireena von Zarovich",
        "Status": "Alive",
        "Portrait": "portraits/ireena-von-zarovich.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Isabella",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Isaias Damasio",
        "Status": "Alive",
        "Portrait": "portraits/isaias-damasio.webp",
        "Campaigns": [
            { "Name": "Menace Under Otari", "Role": "Player", "Player": "Jett", "Description": "a half-elf wizard" }
        ]
    },
    {
        "Name": "Ismark",
        "Status": "Alive",
        "Portrait": "portraits/ismark-kolyanovich.webp",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ismark Kolyanovich (Scaena)",
        "Status": "Alive",
        "Portrait": "portraits/ismark-kolyanovich-scaena.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Itzmin del Prado",
        "Status": "Dead",
        "Portrait": "portraits/itzmin-del-prado.webp",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ivan",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ivana",
        "Status": "Alive",
        "Portrait": "portraits/ivana-boritsi.webp",
        "Campaigns": [
            { "Name": "Borca", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ives Ismarkovich",
        "Status": "Alive",
        "Portrait": "portraits/ives-ismarkovich.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Jari",
        "Status": "Alive",
        "Portrait": "portraits/jari-sur.webp",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "Player", "Player": "Rory", "Description": "a great-eared nightjar aarakocra druid (circle of dragons)" }
        ]
    },
    {
        "Name": "Javenesh",
        "Status": "Alive",
        "Portrait": "portraits/javenesh-stoutclaw.webp",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Jean-Baptiste Escher (Scaena)",
        "Status": "Alive",
        "Portrait": "portraits/jean-baptiste-escher-scaena.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Jenevere",
        "Status": "Alive",
        "Portrait": "portraits/jenevere.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Jery",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ji-me Vidio",
        "Status": "Alive",
        "Portrait": "portraits/ji-me-vidio.webp",
        "Campaigns": [
            { "Name": "Star Wars: Stranded on Parnassos", "Role": "Player", "Player": "Rory", "Description": "a human guardian" }
        ]
    },
    {
        "Name": "Jim Darkmagic",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Jingle Jangle",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Jirko Ismarkovich",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Joan Hargrave",
        "Status": "Dead",
        "Portrait": "portraits/joan-hargrave.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Johannes",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Jord",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Jorn",
        "Status": "Alive",
        "Portrait": "portraits/jorn-horn.webp",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Juniper",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Jutt",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Kala Mabarin",
        "Status": "Alive",
        "Portrait": "portraits/kala-mabarin.webp",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Kallessk",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Kargan Skul",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ker",
        "Status": "Alive",
        "Portrait": "portraits/ker.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Kholtris",
        "Status": "Alive",
        "Portrait": "portraits/kholtris.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Kianna",
        "Status": "Alive",
        "Portrait": "portraits/kianna.webp",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "King Doerdon",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Kira Risk",
        "Status": "Alive",
        "Portrait": "portraits/kira-risk.webp",
        "Campaigns": [
            { "Name": "Menace Under Otari", "Role": "Player", "Player": "Rory", "Description": "a human rogue" }
        ]
    },
    {
        "Name": "Kitty",
        "Status": "Alive",
        "Portrait": "portraits/kitty-windrivver.webp",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "Player", "Player": "Callista", "Description": "a catgirl shifter artificer (alchemist)" }
        ]
    },
    {
        "Name": "Klendisk",
        "Status": "Alive",
        "Portrait": "portraits/klendisk.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Koh Tam",
        "Status": "Alive",
        "Portrait": "portraits/koh-tam.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Kordichai",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Krue",
        "Status": "Alive",
        "Portrait": "portraits/krue-d-avenir.webp",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "Player", "Player": "Rory", "Description": "an owlfolk aarakocra ranger (spell-less hunter)" },
            { "Name": "Tomb of Horrors", "Role": "Player", "Player": "Rory", "Description": "an owlfolk aarakocra ranger (spell-less hunter)" },
            { "Name": "Borca", "Role": "Player", "Player": "Rory", "Description": "an owlfolk aarakocra ranger (spell-less hunter)" },
            { "Name": "Wild Beyond the Witchlight", "Role": "Player", "Player": "Rory", "Description": "an owlfolk-turned-human ranger (spell-less hunter)" },
            { "Name": "City of Eyes", "Role": "Player", "Player": "Rory", "Description": "a human ranger (spell-less hunter)" },
            { "Name": "Re: Strahd", "Role": "Player", "Player": "Rory", "Description": "a human ranger (spell-less hunter)" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "Player", "Player": "Rory", "Description": "a human ranger (spell-less hunter)" }
        ]
    },
    {
        "Name": "Kwalish",
        "Status": "Alive",
        "Portrait": "portraits/kwalish.webp",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Kyward Apostasio",
        "Status": "Alive",
        "Portrait": "portraits/kyward-apostasio.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "Player", "Player": "Jett", "Description": "a rock gnome apothecary (chemist)" }
        ]
    },
    {
        "Name": "La Fata",
        "Status": "Alive",
        "Portrait": "portraits/la-fata.webp",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Lacrymosa",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Lamorna",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Lang",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Larine",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Larisa Sur",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Laurie Weathermay-Foxgrove",
        "Status": "Alive",
        "Portrait": "portraits/laurie-weathermay-foxgrove.webp",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Lemont Sediam Juste",
        "Status": "Alive",
        "Portrait": "portraits/lemont-sediam-juste.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Lif",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Liko",
        "Status": "Alive",
        "Portrait": "portraits/liko.webp",
        "Campaigns": [
            { "Name": "Menace Under Otari", "Role": "Player", "Player": "Connor", "Description": "a leshy bard" }
        ]
    },
    {
        "Name": "Little Balzac",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Little Strahd",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Lottie",
        "Status": "Alive",
        "Portrait": "portraits/charlotte-de-fortuna.webp",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Lucian",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ludmilla Love",
        "Status": "Alive",
        "Portrait": "portraits/ludmilla-love.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Lurker",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Lynx",
        "Status": "Alive",
        "Portrait": "portraits/lynx.webp",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "Player", "Player": "Callista", "Description": "a changeling warlock (astral griffon)" }
        ]
    },
    {
        "Name": "Lyssa von Zarovich",
        "Status": "Alive",
        "Portrait": "portraits/lyssa-von-zarovich.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Madryck Roslof",
        "Status": "Alive",
        "Portrait": "portraits/madryck-roslof.webp",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Magaggog Bootbottle",
        "Status": "Alive",
        "Portrait": "portraits/magaggog-bootbottle.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mani",
        "Status": "Alive",
        "Portrait": "portraits/manilfari-du-cerceau.webp",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "Player", "Player": "Jett", "Description": "an eladrin sorcerer (emotion lord)" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Maria Adelir",
        "Status": "Alive",
        "Portrait": "portraits/maria-adelir.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Marsh",
        "Status": "Alive",
        "Portrait": "portraits/marsh-ruldegost.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "Player", "Player": "Rory", "Description": "a water genasi cleric (life domain)" }
        ]
    },
    {
        "Name": "Mary",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mattrim",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Meff",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Melo Sur",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Melwythorne",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mephistopheles",
        "Status": "Alive",
        "Portrait": "portraits/mephistopheles.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mina",
        "Status": "Alive",
        "Portrait": "portraits/minarthok-lee.webp",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Minsc",
        "Status": "Alive",
        "Portrait": "portraits/minsc.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mirabelle",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mirror Nia",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Molliver",
        "Status": "Alive",
        "Portrait": "portraits/molliver.webp",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Morax",
        "Status": "Dead",
        "Portrait": "portraits/morax.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Morcades Gable",
        "Status": "Dead",
        "Portrait": "portraits/morcades-gable.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mordenkainen",
        "Status": "Alive",
        "Portrait": "portraits/mordenkainen.webp",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Morty",
        "Status": "Alive",
        "Portrait": "portraits/morty.webp",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mr. Light",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mr. Witch",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Myrtle",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" },
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Mystic",
        "Status": "Alive",
        "Portrait": "portraits/mystic.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "Player", "Player": "Callista", "Description": "an infernal tiefling wizard (order of scribes)" }
        ]
    },
    {
        "Name": "Nassari",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Neferon",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Nia",
        "Status": "Alive",
        "Portrait": "portraits/nia-skultrac.webp",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "Player", "Player": "Callista", "Description": "a dhampir rogue (soulknife)" },
            { "Name": "Tomb of Horrors", "Role": "Player", "Player": "Callista", "Description": "a dhampir rogue (soulknife)" },
            { "Name": "Wild Beyond the Witchlight", "Role": "Player", "Player": "Callista", "Description": "a dhampir rogue (soulknife)" },
            { "Name": "City of Eyes", "Role": "Player", "Player": "Callista", "Description": "a dhampir rogue (soulknife)" },
            { "Name": "Re: Strahd", "Role": "Player", "Player": "Callista", "Description": "a dhampir rogue (soulknife)" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "Player", "Player": "Callista", "Description": "a dhampir rogue (soulknife)" }
        ]
    },
    {
        "Name": "Nim",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Nora",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Nostalia",
        "Status": "Alive",
        "Portrait": "portraits/nostalia-romaine.webp",
        "Campaigns": [
            { "Name": "Borca", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Notte von Zarovich",
        "Status": "Alive",
        "Portrait": "portraits/notte-von-zarovich.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "Player", "Player": "Callista", "Description": "a geppettin magus (arcanist)" }
        ]
    },
    {
        "Name": "Nurse Joy",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Oberon",
        "Status": "Alive",
        "Portrait": "portraits/oberon.webp",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ōdachi",
        "Status": "Alive",
        "Portrait": "portraits/odachi.webp",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Oddlewin",
        "Status": "Alive",
        "Portrait": "portraits/oddlewin.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Old Death",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Omin",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Orcades Gable",
        "Status": "Alive",
        "Portrait": "portraits/orcades-gable.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Orishada",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Osybus",
        "Status": "Alive",
        "Portrait": "portraits/osybus.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Otis",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ottelie",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Paloma",
        "Status": "Alive",
        "Portrait": "portraits/paloma.webp",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Patsky",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Pazrodine",
        "Status": "Alive",
        "Portrait": "portraits/pazrodine.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Petre Teodorus",
        "Status": "Alive",
        "Portrait": "portraits/petre-teodorus.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Pewter",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Pidlwick",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Pietra van Riese",
        "Status": "Alive",
        "Portrait": "portraits/pietra-van-riese.webp",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Pollenella",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Porter",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Prismari",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Prydevere",
        "Status": "Alive",
        "Portrait": "portraits/prydevere-milivera.webp",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Quentillius",
        "Status": "Alive",
        "Portrait": "portraits/quentillius-antiphiun-melentor-iii.webp",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Quevven Teh'Kinrellz",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Quincey Pasqual Morris (Scaena)",
        "Status": "Alive",
        "Portrait": "portraits/quincey-pasqual-morris-scaena.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rahadin",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rahadin Zdravkov (Scaena)",
        "Status": "Alive",
        "Portrait": "portraits/rahadin-zdravkov-scaena.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ramius Dangremond",
        "Status": "Alive",
        "Portrait": "portraits/ramius-dangremond.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rampart",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Renaer",
        "Status": "Alive",
        "Portrait": "portraits/renaer-neverember.webp",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" }
        ]
    },
    {
        "Name": "Reynard Ratflea",
        "Status": "Alive",
        "Portrait": "portraits/reynard-ratflea.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rictavio",
        "Status": "Alive",
        "Portrait": "portraits/rudolph-van-richten.webp",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "Tomb of Horrors", "Role": "NPC" },
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "NPC" }
        ]
    },
    {
        "Name": "Risk",
        "Status": "Alive",
        "Portrait": "portraits/risk.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rizzeryl",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Roberta",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Robi Junior (Pidlwick III)",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Roneca",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rosa",
        "Status": "Alive",
        "Portrait": "portraits/rosa.webp",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rosie",
        "Status": "Alive",
        "Portrait": "portraits/rosimyffenbip-wuzfeddlims.webp",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rubina",
        "Status": "Alive",
        "Portrait": "portraits/rubina-larkingdale.webp",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rudolph",
        "Status": "Alive",
        "Portrait": "portraits/rudolph-d-avenir.webp",
        "Campaigns": [
            { "Name": "Borca", "Role": "NPC" },
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ruik",
        "Status": "Alive",
        "Portrait": "portraits/ruik-dwin-anea.webp",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "Player", "Player": "Rory", "Description": "a half-elf paladin (oath of vengeance)" },
            { "Name": "Orrery of the Wanderer", "Role": "Player", "Player": "Rory", "Description": "a half-elf paladin (oath of vengeance)" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "Player", "Player": "Rory", "Description": "a half-elf paladin (oath of vengeance)" }
        ]
    },
    {
        "Name": "Rupert Deadbolt",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ruslana",
        "Status": "Alive",
        "Portrait": "portraits/ruslana-nochnik.webp",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Rusty Bucket",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ruxa",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Sackville Grabbins",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Samira Arah",
        "Status": "Alive",
        "Portrait": "portraits/samira-arah.webp",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Sandman",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Seku Awaud",
        "Status": "Alive",
        "Portrait": "portraits/seku-awaud.webp",
        "Campaigns": [
            { "Name": "Star Wars: Stranded on Parnassos", "Role": "Player", "Player": "Callista", "Description": "a twi'lek scout" }
        ]
    },
    {
        "Name": "Selise",
        "Status": "Alive",
        "Portrait": "portraits/selise-astorio.webp",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "NPC" },
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Serapio",
        "Status": "Alive",
        "Portrait": "portraits/serapio.webp",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Shanix Breakrattle",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Shuvadri",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Sildar",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Silver",
        "Status": "Alive",
        "Portrait": "portraits/silver-lovelysong.webp",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "Player", "Player": "Callista", "Description": "a fairy warlock (archfey)" }
        ]
    },
    {
        "Name": "Sir Talavar",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Skabatha Nightshade",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Skeemo Weirdbottle",
        "Status": "Dead",
        "Portrait": "portraits/skeemo-weirdbottle.webp",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" }
        ]
    },
    {
        "Name": "Skelly",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Skoll",
        "Status": "Alive",
        "Portrait": "portraits/skoll-de-marais.webp",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "Player", "Player": "Jett", "Description": "a river elf druid (circle of the moon)" },
            { "Name": "Tomb of Horrors", "Role": "Player", "Player": "Jett", "Description": "a river elf druid (circle of the moon)" },
            { "Name": "Wild Beyond the Witchlight", "Role": "Player", "Player": "Jett", "Description": "a river elf druid (circle of the moon)" },
            { "Name": "City of Eyes", "Role": "Player", "Player": "Jett", "Description": "a river elf druid (circle of the moon)" },
            { "Name": "Re: Strahd", "Role": "Player", "Player": "Jett", "Description": "a river elf druid (circle of the moon)" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "Player", "Player": "Jett", "Description": "a river elf druid (circle of the moon)" }
        ]
    },
    {
        "Name": "Sonja Florakis",
        "Status": "Alive",
        "Portrait": "portraits/sonja-florakis.webp",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "Player", "Player": "Connor", "Description": "a half-elf bard (college of spirits)" }
        ]
    },
    {
        "Name": "Stella von Zarovich",
        "Status": "Alive",
        "Portrait": "portraits/stella-von-zarovich.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Strahd",
        "Status": "Alive",
        "Portrait": "portraits/strahd-von-zarovich.webp",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Strashka Relvaunder",
        "Status": "Alive",
        "Portrait": "portraits/strashka-relvaunder.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Struthio",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Sumari",
        "Status": "Alive",
        "Portrait": "portraits/sumari.webp",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "Player", "Player": "Jett", "Description": "a wildhunt shifter warden (verdant protector)" }
        ]
    },
    {
        "Name": "Sylqen Silverwatch",
        "Status": "Alive",
        "Portrait": "portraits/sylqen-silverwatch.webp",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Synestia Whitechapel",
        "Status": "Alive",
        "Portrait": "portraits/synestia-whitechapel.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Talanatha",
        "Status": "Alive",
        "Portrait": "portraits/talanatha-three-coins.webp",
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Tashlyn",
        "Status": "Alive",
        "Portrait": "portraits/tashlyn-yafeera.webp",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Telphusa",
        "Status": "Alive",
        "Portrait": "portraits/telphusa.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ten",
        "Status": "Alive",
        "Portrait": "portraits/ten.webp",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Tenser",
        "Status": "Alive",
        "Portrait": "portraits/tenser.webp",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Thaco",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Thalia",
        "Status": "Alive",
        "Portrait": "portraits/thalia.webp",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "The Abbot (Jude Law)",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "The Cat Lord",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "The Fisher King",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "The Painted Lady",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "The Spider",
        "Status": "Dead",
        "Portrait": "portraits/the-spider.webp",
        "Campaigns": [
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Thetsis",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Tiax",
        "Status": "Alive",
        "Portrait": "portraits/tiax.webp",
        "Campaigns": [
            { "Name": "Chains of Asmodeus", "Role": "NPC" }
        ]
    },
    {
        "Name": "Tilana",
        "Status": "Alive",
        "Portrait": "portraits/tilana-kapule.webp",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Titan",
        "Status": "Alive",
        "Portrait": "portraits/titan.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "To'vvag'das'vak'thur'ai'thumonic'ar of the Greater Eye",
        "Status": "Alive",
        "Portrait": "portraits/to-vvag-das-vak-thur-ai-thumonic-ar-of-the-greater-eye.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Tordit",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Trench",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" }
        ]
    },
    {
        "Name": "Trilla",
        "Status": "Alive",
        "Portrait": "portraits/trilla.webp",
        "Campaigns": [
            { "Name": "Volo's Guide to Getting Murdered", "Role": "Player", "Player": "Connor", "Description": "a half-orc rogue (seeker)" }
        ]
    },
    {
        "Name": "Tsu",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Tullus",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Tungsten Ward",
        "Status": "Alive",
        "Portrait": "portraits/tungsten-ward.webp",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Tzunk",
        "Status": "Alive",
        "Portrait": "portraits/tzunk.webp",
        "Campaigns": [
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Urzmaktok",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Vajra",
        "Status": "Alive",
        "Portrait": "portraits/vajra-safahr.webp",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "NPC" }
        ]
    },
    {
        "Name": "Vasilka (Scaena)",
        "Status": "Alive",
        "Portrait": "portraits/vasilka-scaena.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Velastrias",
        "Status": "Alive",
        "Portrait": "portraits/velastrias-shaerival.webp",
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Victor",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Victor Vallakovich (Scaena)",
        "Status": "Alive",
        "Portrait": "portraits/victor-vallakovich-scaena.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Vih'zel",
        "Status": "Alive",
        "Portrait": "portraits/vih-zel-amreth.webp",
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "Player", "Player": "Callista", "Description": "a githyanki fighter (echo knight)" }
        ]
    },
    {
        "Name": "Vito Romenza",
        "Status": "Alive",
        "Portrait": "portraits/vito-romenza.webp",
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Volenta Popofsky (Scaena)",
        "Status": "Alive",
        "Portrait": "portraits/volenta-popofsky-scaena.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Volo",
        "Status": "Alive",
        "Portrait": "portraits/volothamp-geddarm.webp",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" },
            { "Name": "Volo's Guide to Getting Murdered", "Role": "NPC" }
        ]
    },
    {
        "Name": "Vyldara",
        "Status": "Dead",
        "Portrait": "portraits/vyldara.webp",
        "Campaigns": [
            { "Name": "Objects of Interest: Forged in Fire", "Role": "NPC" }
        ]
    },
    {
        "Name": "Wester",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Whippoorwill",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Whisper",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Will of the Feywild",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Wizzy",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Orrery of the Wanderer", "Role": "NPC" }
        ]
    },
    {
        "Name": "Wobbles",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Woe Ismae",
        "Status": "Alive",
        "Portrait": "portraits/woe-ismae.webp",
        "Campaigns": [
            { "Name": "Star Wars: Stranded on Parnassos", "Role": "Player", "Player": "Jett", "Description": "a zabrak consular" }
        ]
    },
    {
        "Name": "Yagra",
        "Status": "Alive",
        "Portrait": "portraits/yagra-stonefist.webp",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" },
            { "Name": "Orrery of the Wanderer", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Yarnspinner",
        "Status": "Alive",
        "Portrait": "portraits/yarnspinner.webp",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    },
    {
        "Name": "Yek",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Yesper",
        "Status": "Alive",
        "Portrait": "portraits/yesper-taltos.webp",
        "Campaigns": [
            { "Name": "Curse of Strahd", "Role": "NPC" },
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" },
            { "Name": "City of Eyes", "Role": "NPC" }
        ]
    },
    {
        "Name": "Yesper Taltos (Scaena)",
        "Status": "Alive",
        "Portrait": "portraits/yesper-taltos-scaena.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ygor",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Journeys through the Radiant Citadel", "Role": "NPC" }
        ]
    },
    {
        "Name": "Yurk",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" },
            { "Name": "Lost Laboratory of Kwalish", "Role": "NPC" }
        ]
    },
    {
        "Name": "Yves Kolyanovich",
        "Status": "Alive",
        "Portrait": "portraits/yves-kolyanovich.webp",
        "Campaigns": [
            { "Name": "Re: Strahd", "Role": "Player", "Player": "Connor", "Description": "a hexblood cleric (life domain)" }
        ]
    },
    {
        "Name": "Zanther",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Zaria",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Strixhaven: Year 1", "Role": "NPC" }
        ]
    },
    {
        "Name": "Zilitsa",
        "Status": "Alive",
        "Portrait": null,
        "Campaigns": [
            { "Name": "Dungeon of the Mad Mage", "Role": "NPC" }
        ]
    },
    {
        "Name": "Ziraj",
        "Status": "Alive",
        "Portrait": "portraits/ziraj.webp",
        "Campaigns": [
            { "Name": "Waterdeep: Dragon Heist", "Role": "NPC" }
        ]
    },
    {
        "Name": "Zybilna",
        "Status": "Alive",
        "Portrait": "portraits/zybilna.webp",
        "Campaigns": [
            { "Name": "Wild Beyond the Witchlight", "Role": "NPC" }
        ]
    }
];
